apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  AWS_ACCESS_KEY: QUtJQVZWTUNZRlNEMko1Vlc3SVY=
  AWS_SECRET_KEY: dVQ2K2dReTRqNldMWmdnRlZ5Y3lHWkc3V3F1VUpId0lSU0tiN2hWUQ==
  NETBOXTOKEN: VG9rZW4gMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nw==